# Stage 1 - the build process
FROM node:10.18.1 as build-deps
ENV REACT_APP_API_URL=https://api.worklife-beyond.com
ENV REACT_APP_GRAPHQL_URL=https://gql.worklife-beyond.com/v1/graphql
ENV REACT_APP_GRAPHQL_URL_WS=wss://gql.worklife-beyond.com/v1/graphql
ENV REACT_APP_AUTH_URL=https://auth.worklife-beyond.com/api/user
ENV REACT_APP_BASE_APP_URL=http://app.worklife-beyond.com
ENV REACT_APP_COOKIE=.worklife-beyond.com
ENV REACT_APP_API_URL_PCS=https://sosmed.worklife-beyond.com/v1

WORKDIR /usr/src/app
COPY package.json yarn.lock ./
RUN yarn
COPY . ./
RUN yarn build

# Stage 2 - the production environment
FROM nginx:1.12-alpine
COPY default.conf /etc/nginx/conf.d/default.conf
COPY --from=build-deps /usr/src/app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
