# Stage 1 - the build process
FROM node:8.10.0 as build-deps
ENV REACT_APP_API_URL=https://poseidon.worklifebeyond.com
ENV REACT_APP_GRAPHQL_URL=https://neptune.worklifebeyond.com/v1/graphql
ENV REACT_APP_GRAPHQL_URL_WS=wss://neptune.worklifebeyond.com/v1/graphql
ENV REACT_APP_AUTH_URL=https://auth.worklifebeyond.com/api/user
ENV REACT_APP_DEPENDENT_URL=https://hc.worklifebeyond.com
ENV REACT_APP_BASE_APP_URL=http://app.worklifebeyond.com
ENV REACT_APP_COOKIE=.worklifebeyond.com


WORKDIR /usr/src/app
COPY package.json yarn.lock ./
RUN yarn
COPY . ./
RUN yarn build

# Stage 2 - the production environment
FROM nginx:1.12-alpine
COPY default.conf /etc/nginx/conf.d/default.conf
COPY --from=build-deps /usr/src/app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
